### ISSUE TITLE
Retry transient errors like network timeout

### ISSUE THREAD

**Issue by samtstern** [firebase/oss-bot#44]
In the most recent report, quickstart-ios had no snapshot:
<img width="1132" alt="screen shot 2019-01-23 at 11 01 10 am" src="https://user-images.githubusercontent.com/8466666/51630176-52220b00-1efe-11e9-8f69-b9cea0203c9c.png">

```
HttpError: network timeout at: https://api.github.com/repos/firebase/quickstart-ios/issues?access_token=a00421fbfda0a8af79cf843955b2d3816ab0f8f7&per_page=100&page=2&state=all
    at mockable.fetch.then.then.catch.error (/srv/node_modules/@octokit/request/lib/request.js:92:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

We should increase the timeout of the HTTP client and add retrying into GitHub pagination.

cc @morganchen12

**Comment by samtstern** [comment]
This has been solved by using the Octokit Retry thingy.
